name: Anchore SBOM Action

on:
  workflow_dispatch:

jobs:
  sbom_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Anchore SBOM Action
        uses: anchore/sbom-action@v0.15.10
        with:
          path: "."
          format: "spdx-json"
          github-token: "${{ github.token }}"
          dependency-snapshot: "false"
          upload-artifact: "true"
          upload-artifact-retention: "0"
          upload-release-assets: "true"
